-- descriptions/images from IMDB
INSERT INTO movies (title, description, genre, image) VALUES ( 'Billy Madison', 'In order to inherit his fed up fathers hotel empire, an immature and lazy man must repeat grades 1-12 all over again.', 'Comedy', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMzcyMjZmNjctNGNhMS00ZmQxLWFkNzQtYTIxYjVkYmU1NmNmXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg');
INSERT INTO movies (title, description, genre, image) VALUES ( 'Saving Private Ryan', 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.', 'Action', 'https://images-na.ssl-images-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UY268_CR0,0,182,268_AL_.jpg');
INSERT INTO movies (title, description, genre, image) VALUES ( 'Crank', 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.', 'Action', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjg0NjAxNDY4MV5BMl5BanBnXkFtZTcwODA5MjMzMw@@._V1_UX182_CR0,0,182,268_AL_.jpg'); 
INSERT INTO movies (title, description, genre, image) VALUES ( 'Happy Gilmore', 'A rejected hockey player puts his skills to the golf course to save his grandmothers house.', 'Comedy', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjA4NjUxODg3Ml5BMl5BanBnXkFtZTcwNzcyODc5Mw@@._V1_UX182_CR0,0,182,268_AL_.jpg');
INSERT INTO movies (title, description, genre, image) VALUES ( 'BASEketball', 'Two childhood friends are pro athletes of a national sport called BASEketball, a hybrid of baseball and basketball, and must deal with a greedy businessman scheming against their team.', 'Comedy', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMmZjZDg2ZjItYTVkNC00YWRmLThmZTMtNTYxNTI5MWM4NjU4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg');
INSERT INTO movies (title, description, genre, image) VALUES ( 'Hannibal', 'Living in exile, Hannibal Lecter tries to reconnect with now disgraced F.B.I. Agent Clarice Starling, and finds himself a target for revenge from a powerful victim.', 'Thriller', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNTcxYTVhNjYtYmRkZC00NWIwLTliZGYtYmQyODE3OTNmYzBiXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX182_CR0,0,182,268_AL_.jpg');
INSERT INTO movies (title, description, genre, image) VALUES ( 'Semi-pro', 'Jackie Moon, the owner-coach-player of the American Basketball Associations Flint Michigan Tropics, rallies his teammates to make their NBA dreams come true.', 'Comedy', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTc1MjQ4NTc3M15BMl5BanBnXkFtZTcwMTc3NTg1MQ@@._V1_UY268_CR0,0,182,268_AL_.jpg');
INSERT INTO movies (title, description, genre, image) VALUES ( 'Austin Powers in Goldmember', 'Upon learning that his father has been kidnapped, Austin Powers must travel to 1975 and defeat the aptly named villain Goldmember, who is working with Dr. Evil.', 'Comedy', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTkzNTk3Mzk1MF5BMl5BanBnXkFtZTYwMzM5NDA5._V1_UX182_CR0,0,182,268_AL_.jpg');
INSERT INTO movies (title, description, genre, image) VALUES ( 'Zoolander', 'At the end of his career, a clueless fashion model is brainwashed to kill the Prime Minister of Malaysia.', 'Comedy', 'https://images-na.ssl-images-amazon.com/images/M/MV5BODI4NDY2NDM5M15BMl5BanBnXkFtZTgwNzEwOTMxMDE@._V1_UX182_CR0,0,182,268_AL_.jpg');
INSERT INTO movies (title, description, genre, image) VALUES ( 'Inglorious Basterds', 'In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owners vengeful plans for the same.', 'Adventurer', 'https://images-na.ssl-images-amazon.com/images/M/MV5BOTJiNDEzOWYtMTVjOC00ZjlmLWE0NGMtZmE1OWVmZDQ2OWJhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_UX182_CR0,0,182,268_AL_.jpg');